config/routes.rb
Rails.application.routes.draw do
  resources :albums
  get 'home/main'
  get '/albums/:id' ,to: 'albums#destroy', as: 'albums_destroy'

  resources :albums do
    member do
       delete :delete_album_photos
    end
 end

  devise_for :users do
    resources :albums 
  end
  get '/albums/:id/delete_album_photos', to: 'albums#delete_album_photos'

  root 'home#main'
  
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    end

end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"
    validates :title, presence: true
    validates :decription, presence: true
    has_many_attached :album_photos , dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_many :album, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_user

    def index
        @album = @user.album
        render 'albums/index'
    end
    def show
        @album = Album.find(params[:id])
    end
    
    def new
        @album = Album.new
    end
    def create
        @album = Album.new(album_params)
        @album = @user.album.create(album_params)
        if @album.save
            redirect_to @album
        else
            render :new
        end
    end
    def edit
        @album = Album.find(params[:id])
    end
    def update
        @album = Album.find(params[:id])
        # @album = @user.album.create(album_params)
        if @album.update(album_params)
            redirect_to @album
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @album = Album.find(params[:id])
        @album.destroy

        redirect_to albums_path, status: :see_other
    end
    def delete_album_photos
        attachment = ActiveStorage::Attachment.find(params[:id])
        attachment.purge
        redirect_back(fallback_location: albums_path)
     end
    
    
    private
    def album_params
        params.require(:album).permit(:title, :decription, album_photos: [])
    end
    def set_album
        @album = Album.find(params[:id])
     end
    def set_user
        @user = User.find(current_user.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<div class = "d-flex justify-content-center">
<%= form_with model: @album do |form| %>
  <div>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% if @album.errors.any? %>
      <% @album.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= form.label :decription %><br>
    <%= form.text_field :decription %>
    <% if @album.errors.any? %>
      <% @album.errors.full_messages_for(:decription).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :Choose_Photos_For_Album %><br>
    <%= form.file_field :album_photos, multiple: true %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<br>
<%= link_to "Back", albums_path, style: "display: block;width: 115px;height: 46px;background: #212529;padding: 10px;text-align: center;border-radius: 5px;color: white;font-weight: bold; text-decoration: none; margin: auto;line-height: 25px;" %>
</div>
</div>

app/views/albums/edit.html.erb
<%= render "form" %>

app/views/albums/index.html.erb
<h1>Albums</h1>
<h4>Your currently generated Albums: </h4>
<%@album.each do |album|%>
    <ul>
        <li>
            <%= link_to album.title, album, style: "text-decoration:none; color: #000;" %>
        </li>
    </ul>
<% end %>
<%= link_to "New Album", new_album_path, style: "display: block;width: 115px;height: 46px;background: #212529;padding: 10px;text-align: center;border-radius: 5px;color: white;font-weight: bold; text-decoration: none; margin-left: 10px;line-height: 25px;" %>

app/views/albums/new.html.erb
<%= render "form" %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<h4><%= @album.decription %></h4>

<ul>
    <li>
        <%= link_to "Edit", edit_album_path(@album) , style: "text-decoration:none; color: #000;"%>
    </li>
    <li>
        <%= link_to "Destroy", albums_destroy_path(@album), data:
        {
            turbo_method: :delete,
            turbo_confirm: "Are you Sure?"
        }, style: "text-decoration:none; color: #000;" %>
    </li>
</ul>

<%= link_to "Back", albums_path, style: "display: block;width: 115px;height: 46px;background: #212529;padding: 10px;text-align: center;border-radius: 5px;color: white;font-weight: bold; text-decoration: none; margin-left: 10px;line-height: 25px;"%>

<hr>
<h1>Photos: </h1>
<div class="container" style="max-width: 1700px;">
<% @album.album_photos.order("created_at DESC").each do |album_photos| %>
<div style="margin: 5px;border: 1px solid #ccc;float: left;width: 195px;">
<%= link_to image_tag(album_photos.variant(resize_to_fill: [195, 195]), style: "width: 100%;height: auto;", alt: album_photos.filename.to_s), album_photos, target: "_blank"%>

<div style="padding: 8px;text-align: center;font-size: 0.7em">
<%= link_to 'Delete', delete_album_photos_album_path(album_photos), method: :delete, data: { confirm: 'Are you sure?' }, style: "text-decoration:none; color: #000;" %>
</div>
</div>
<% end %>
</div>

app/views/home/main.html.erb
<h1>Rails Assignment</h1>
<ul>
    <li>Create a simple rails application.</li>
    <li>Use devise gem for authentication.</li>
    <li> User can have many albums(name and description) and album can have many photos.</li>
    <li>There will be album new/edit form. Ability to delete the album. Ability to delete associated photos individually and along with on delete of a album.</li>
    <li>On the album new/edit form, user should be able to upload multiple photos. Should be done using accepts_nested_attributes for multimodel form.</li>
    <li>Photos can also have multiple tags(comma separated) (Don't use any tagging plugin/gem). Album and associated photos with tags should be created simultaneously as explained in the previous point as well.</li>
    <li>Include necessary Unit and Functional tests.</li>
    <li>Deploy the app to heroku(https://www.heroku.com) using github.</li>
</ul>
<br>
<p>Note: Don't use Scaffolding anywhere.</p>

<hr style="border: 4px solid black;">

<% if current_user %>
        <p>Hello, <%= current_user.email %>!!!</p>
        <p>View Your Albums: <a href="/albums">Albums</a></p>
<% else %>
    <p>You are not signed in!!!</p>
    <p>To create a new account: </p>
    <ul>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
    </ul>
    <p>Or, if you are connected with us: </p>
    <ul>    
        <li>
            <p>Please <%= link_to "Login", new_user_session_path %> with your credentials</p>
        </li>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allbum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-WWKKC89TML"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WWKKC89TML');
  </script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Album App", root_path, class: 'css_class', style: 'color:#FFFFFF; text-decoration:none; font-size:1.5rem' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li> <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" style="background-color:#212529; border-color: #212529;" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Alias</button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><%= link_to "Edit your profile", edit_user_registration_path , class: "dropdown-item",style: 'color:#000; text-decoration:none; font-size:1rem; justify-content: center'%></li>
    <li><hr class="dropdown-divider"></li>
    <%= link_to "Sign Out", destroy_user_session_path, class: 'dropdown-item',style: 'color:#000; text-decoration:none; font-size:1rem; justify-content: center' %></li>
  </ul>
</div>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>